#!/bin/sh

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
cd $DIR

if [ -f /EON ]; then
  export LD_LIBRARY_PATH="/data/pythonpath/third_party/snpe/aarch64/:$LD_LIBRARY_PATH"
else
  export LD_LIBRARY_PATH="$DIR/../../third_party/snpe/x86_64-linux-clang:$DIR/../../openpilot/third_party/snpe/x86_64:$LD_LIBRARY_PATH"
fi
old_model="0"
if [ -f /data/params/d/dp_0813 ]; then
  old_model=`cat /data/params/d/dp_0813`
fi
if [ $old_model == "1" ]; then
  exec ./_modeld_0813
else
  exec ./_modeld
fi
